name: NewMod-Core
main: me.bergenfly.newmod.core.NewModPlugin
version: Pre-Alpha
api-version: 1.21.8
commands:
  nm:
    description: Mod commands
  ff:
    description: Mod commands
  griefChunk:
    description: :3
depend:
  - ProtocolLib