name: Nations
main: me.bergenfly.nations.NationsPlugin
version: 1.0.0
api-version: 1.21
commands:
  settlement:
    aliases: [town, t, s, set]
  nation:
    aliases: [n, nat]
  plot:
  tribe:
  community:
  company:
    aliases: [comp]